### PR TITLE
add Dial Templates default timeout

### PR DESCRIPTION
**Pull request by joele89**

### CODE REVIEW

**Comment by gareth-palmer** [comment]
The text should say "if you do not specify a dial template" instead of "if you don't create a Dial Template" as one may be created but not specified.

I wonder if that 15s timeout is `<offhookToFirstDigitTimer>`, that should be checked.

The documentation doesn't use an italicised "Important" for notable information, instead it uses a bold "Note".

**Comment by joele89** [comment]
Understood, will make the adjustments in the text.

I will test changes to `<offhookToFirstDigitTimer>`, however the text suggests that it's a different part of the process.

**Comment by joele89** [comment]
I have also added a similar note to the Dial Templates page

**Comment by gareth-palmer** [comment]
Did `<offhookToFirstDigitTimer>` change the behaviour? Options that relate to dialing both having a value of 15s might be more than coincidental 

Revert the change to dial-templates.html as I only want the note on the SEPMAC.cnf.xml for now.

Also, the ':' shouldn't be bolded, ie: `<b>Note</b>:`.

**Comment by joele89** [comment]
I have confirmed that the `<offhookToFirstDigitTimer>` does not impact the wait time associated with dial templates (offhook is before dialing, dial templates set after dialing wait).

**Comment by gareth-palmer** [comment]
Contractions (don't, isn't, wasn't etc.) are to be avoided in formal text.
Dial Template does not need to be capitalized.
Have the text exactly be:
> default timeout is 15 seconds if you don not specify a dial template.

**Pull request merged**
