### PR TITLE
Add 'authPassword' length limits to sepmac-cnf-xml.html

### PR DESCRIPTION
**Pull request by joele89**

### CODE REVIEW

**Comment by gareth-palmer** [comment]
The password length limits probably the same for all models as it will be whatever CUCM uses. Otherwise the table needs to contain at least the limits for 6900, 7800, 7900 and 8800 series phones.

The limits for the other string fields (authName, featureLabel) should be documented at the same time.

The limit in the PR is for 6700 which does not appear to be a valid phone series.

**Comment by joele89** [comment]
Appoligies, typo with the model number, should read 7900.
Agree that the password length limit is likely universal, independent documentation I've more recently come across also suggests this.

I only have a 7962 available for testing, but will report back on length limits for authName and featureLabel

**Comment by joele89** [comment]
With FreePBX auto generating it's secret's at 32 characters, do you want to include a note about this too?
I believe this would be the first reference to FreePBX across the documentation so may feel incosistent.

**Comment by gareth-palmer** [comment]
I am not sure how these limits are being tested as those numbers seem odd.

Cisco publish a list of the tables used by CUCM called the Data Dictionary: https://developer.cisco.com/docs/axl/15-cucm-data-dictionary/

The `devicenumplanmap` table seems to be the source for line keys. The validation regexp shows that it accepts up to 30 characters.

Use that limit for all the fields. 

The limit text needs to exactly match that used by `<phoneLabel>`.

`<name>` also needs the length limit text.

**Comment by joele89** [comment]
Testing by simply adding a character at a time until the phone fails to register. (Except featureLabel which was until the phone automatically added an ellipse, it continued to accept characters beyond that but they were meaningless)

**Comment by joele89** [comment]
It looks like the field length limit for authUsername is affected by the processNodeName and the displayName. As these are combined to complete the authentication ie. `displayName` <`authUsername`@`processNodeName`>. This appears to have a practical limit of 80 characters.
In my case this allowed a username up to ~70 characters, but milage may vary. 

Diving further into the validation rules, it looks like the maximum hostname validation is ~50 characters, add this to the username validation at ~30 characters gets to the practical limit I was reaching.

For some reason most of those validation rules are 31 characters instead of 30 (or a nice round number, but +1), not sure how to approach that...

Should we also document the 50 character length limit on the `processNodeName` being implied by the Data Dictionary?

**Comment by gareth-palmer** [comment]
Okay, the hostname lengths can be documented as well. There as some others that need to have limits mentioned.

`<displayName>` for `<line>`, another 30 character field.

`<address>` for `<TVS> ... <member>`, a 50 character field.
`<name>` for `<ntp>`, another 50 character field.

`<url1>` for `<vpnGroup> ... <addresses>` is a 255 character field.
`<servicesURL>`, `<directoryURL>`, `<messagesURL>` etc. are 255 character fields.
`<url>` for `<phoneServices>` is a 255 character field.

**Comment by gareth-palmer** [comment]
Looks good to me.

**Pull request merged**
